config/routes.rb
Thecolbyecho::Application.routes.draw do

  resources :ledes
  resources :people
  resources :photos
  resources :departments
  resources :articles
  resources :issues do 
    resources :articles
  end

  Department.all.each do |dept|
    get dept.slug => 'departments#show', :slug => dept.slug 
    get dept.slug+'/:slug' => 'articles#show', department: dept.slug 
  end

  # TODO: change when sessions are hooked up
  get 'sonar' => 'sessions#create', :slug => 'sonar'
  get 'logout'   => 'sessions#destroy', :slug => 'logout'


  root :to => 'frontpage#index'
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :bio, :email, :name, :photo_id, :position, :slug, :year
  has_and_belongs_to_many :articles
  validates_presence_of :name
  validates_presence_of :slug
  validates_uniqueness_of :slug
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all
    @groups = ['admin', 'contributors', 'laypeople']

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :photo_id %><br />
    <%= f.number_field :photo_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<div class="grids">
  <div class="grid-6">
    <%= render 'form' %>
    <%= link_to 'Show', @person %> |
    <%= link_to 'Back', people_path %>
  </div>
</div>

app/views/people/index.html.erb
<h1 class="mfb">People</h1>

<div class="grids">

  <div class="grid-9">
    <div class="mky">
      <div class="grids">
        <% @people.each do |person| %>
          <div class="grid-4">
            <div class="mob">
              <h3><%= link_to person.name, person %></h3>
              <div class="mct"><%= person.email %></div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="grid-3">
    <aside class="mky">
      <section class="pf mfb">
        <span>TODO: Link to instructions and list of people who want to join</span>
      </section>
      <% @groups.each do |group| %>
        <section class="pf mfb">
          <%= link_to group.capitalize, '/people?group='+group %>
        </section>
      <% end %>

      <section class="pf mfb">
        <a href="">People requesting access</a>  
      </section>

    </aside>
  </div>

</div>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class="grids pky">
  <div class="grid-8">

    <div class="grids">
      <% @person.articles.each do |a| %>
        <div class="grid-4 pfb">
          <%= render :partial => "shared/article_grid", :locals => {:article => a} %> 
        </div>
      <% end %>
    </div>

  </div>
  <div class="grid-4">

    <!-- TODO: their photo -->
    <!-- Profile picture -->
    <div class="mfb">
      <img src="http://placekitten.com/400/300" class="full" />
    </div>

    <!-- Basic information -->
    <div class="mfb">
      <div class="si serif mcb">
        <%= @person.name %>
      </div>

      <% if @person.year %>
        <div>Class of <%= @person.year %></div>  
      <% end %>

      <% if @person.position %>
        <div><%= @person.position %></div>  
      <% end %>

      <% if @person.bio %>
        <div><%= @person.bio %></div>  
      <% end %>

      <% if current_user %>
        <div class="pkt">
          <%= link_to 'Edit', edit_person_path(@person) %>
        </div>
      <% end %>
    </div>

  </div>
</div>