config/routes.rb
Thecolbyecho::Application.routes.draw do

  resources :ledes
  resources :people
  resources :photos
  resources :departments
  resources :articles
  resources :issues do 
    resources :articles
  end

  Department.all.each do |dept|
    get dept.slug => 'departments#show', :slug => dept.slug 
    get dept.slug+'/:slug' => 'articles#show', department: dept.slug 
  end

  # TODO: change when sessions are hooked up
  get 'sonar' => 'sessions#create', :slug => 'sonar'
  get 'logout'   => 'sessions#destroy', :slug => 'logout'


  root :to => 'frontpage#index'
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :name, :public, :volume, :edition, :publish_date 
  has_many :articles

  def self.latest_published_issue
    Issue.limit(1).order('publish_date DESC').where('public = ?', true).first
  end

  def self.volume_year_range(volume)
    @issues = Issue.where('volume=?', volume)
    latest = @issues.order('publish_date DESC').first 
    earliest = @issues.order('publish_date ASC').first 
    #earliest.publish_date+" - "+latest.publish_date
  end
end

app/models/issues.rb
class Issues < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  def index
    if params[:volume]
      @issues = Issue.order('publish_date DESC').where('volume = ?', params[:volume])
    else
      @issues = Issue.order('publish_date DESC')
    end
    @volumes = Issue.uniq.pluck(:volume).sort.reverse
    #@volumes.map {|v| v[:year_range] = Issue.volume_year_range(v)}
  end

  def new
    @issue = Issue.new
  end

  def edit 
    @issue = Issue.find(params[:id])
  end

  def create
    @issue = Issue.new(params[:issue])

    if @issue.save
      redirect_to issues_url, notice: 'Issue was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @issue = Issue.find(params[:id])

    if @issue.update_attributes(params[:issue])
      redirect_to issues_url, notice: 'Issue was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy
    redirect_to issues_url
  end

end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.label :edition %>
    <%= f.text_field :edition %>
  </div>

  <div class="actions">
    <%= f.label :volume %>
    <%= f.text_field :volume %>
  </div>

  <div class="actions">
    <%= f.label :public %>
    <%= f.check_box :public %>
  </div>

  <div class="actions">
    <%= f.label :publish_date %>
    <%= f.date_select :publish_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<div class="grids">

  <div class="grid-8">
    <div class="mky">
      <%= render 'form' %>
    </div>
  </div>

  <div class="grid-4">
    <aside class="mky">
      <section class="pf mfb">
        <%= link_to 'Back to Issues', issues_url %>
      </section>
    </aside>
  </div>

</div>

app/views/issues/index.html.erb
<h1>Issues <span class="ligrey fwn pbl">volume <%= params[:volume] %>, 2013 - 2014</span></h1>

<div class="grids">

  <div class="grid-8">
    <div class="mky">
      <% @issues.each do |issue| %>
        <div class="mob">
          <h2><%= issue.name %></h2>
          <% if issue.public %>
            <div class="bg-green mdy pd fwb">
              <span class="dib mfr">public</span>
          <% else %>
            <div class="bg-orange mdy pd fwb">
              <span class="dib mfr">invisible</span>
          <% end %>
            <span class="dib mfr"><%= link_to 'edit', edit_issue_path(issue) %></span>
            <span class="dib mfr"><%= issue.publish_date %></span>
            <span class="dib mfr">Volume <%= issue.volume %></span>
            <span class="dib mfr">Edition <%= issue.edition %></span>
            <!-- TODO: make this link work in a nested fashion -->
            <span class="dib mfr"><%= link_to "New Article", new_article_path %></span>
          </div>
          <% if issue.articles.any? %>
            <div class="grids">
              <% issue.articles.each do |a| %>
                <div class="grid-3">
                  <div class="mfb pc bad">
                    <% if !a.photos.empty? && a.photos.first.image %>
                      <a href="/articles/<%= a.id.to_s  %>" class="db mbb">
                        <%= image_tag a.photos.first.image.url(:square), class: 'full' %>
                      </a>
                    <% end %>
                    <div class="sc mbb"><%= a.department ? a.department.name : "no department" %></div>
                    <div><%= link_to a.headline, edit_article_path(a), class: 'sd' %></div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="grid-4">
    <aside class="mky">
      <section class="pf mfb">
        <%= link_to 'New Issue', new_issue_path %>
      </section>
      <% @volumes.each do |vol| %>
        <section class="pf mfb">
          <%= link_to 'Volume '+vol.to_s, '/issues?volume='+vol.to_s %>
        </section>
      <% end %>
    </aside>
  </div>

</div>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>