config/routes.rb
Thecolbyecho::Application.routes.draw do

  resources :ledes
  resources :people
  resources :photos
  resources :departments
  resources :articles
  resources :issues do 
    resources :articles
  end

  Department.all.each do |dept|
    get dept.slug => 'departments#show', :slug => dept.slug 
    get dept.slug+'/:slug' => 'articles#show', department: dept.slug 
  end

  # TODO: change when sessions are hooked up
  get 'sonar' => 'sessions#create', :slug => 'sonar'
  get 'logout'   => 'sessions#destroy', :slug => 'logout'


  root :to => 'frontpage#index'
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :name, :slug, :outlet 
  validates :slug, uniqueness: true
  has_many :articles
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  def show
    if params[:slug]
      @department = Department.find_by_slug params[:slug]
    else
      @department = Department.find(params[:id])
    end

    if @department 
      if @department.name.downcase == 'blog'
        @articles = @department.articles.limit(10)
        render 'departments/blog' 
      else
        @issue = Issue.latest_published_issue
        @current_articles = @department.articles.where('issue_id = ?', @issue.id)
        @older_articles = @department.articles.where('issue_id = ?', @issue.id)
      end
    else
      redirect_to :root 
    end

  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/blog.html.erb
<h1>Bloog</h1>

<% @articles.each do |a| %>
  <h1><%= @article %></h1>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Slug</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departments.each do |department| %>
  <tr>
    <td><%= department.name %></td>
    <td><%= department.slug %></td>
    <td><%= department.type %></td>
    <td><%= link_to 'Show', department %></td>
    <td><%= link_to 'Edit', edit_department_path(department) %></td>
    <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<div class="grids">

  <div class="grid-12">
    <div class="mhy">
      <h2><%= link_to @department.name, '/'+@department.slug %></h2>
      <div>Published: <%= @issue.publish_date %></div>
    </div>
  </div>

  <% @current_articles.each do |a| %>
    <div class="grid-4">
      <div class="mob">
        <% if !a.photos.empty? && a.photos.first.image %>
          <a href="/articles/<%= a.id.to_s  %>">
            <%= image_tag a.photos.first.image.url(:medium), class: 'full' %>
          </a>
        <% end %>
        <h3 class="serif mbb"><%= link_to a.headline, a %></h3>
        <div class="info mcb"><%= raw a.authors_text %></div>
        <p><%= a.deck %></p> 
      </div>
    </div>
  <% end %>

</div>
<!--
<div class="mot mkb">
  <h2>Older issues</h2>
</div>

<div class="grids">

  <div class="grid-4">
    <div class="">
      <h4>Issue blah</h4>
      article
    </div>
  </div>

</div>
-->