config/routes.rb
Thecolbyecho::Application.routes.draw do

  resources :ledes
  resources :people
  resources :photos
  resources :departments
  resources :articles
  resources :issues do 
    resources :articles
  end

  Department.all.each do |dept|
    get dept.slug => 'departments#show', :slug => dept.slug 
    get dept.slug+'/:slug' => 'articles#show', department: dept.slug 
  end

  # TODO: change when sessions are hooked up
  get 'sonar' => 'sessions#create', :slug => 'sonar'
  get 'logout'   => 'sessions#destroy', :slug => 'logout'


  root :to => 'frontpage#index'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :caption, :extension, :person_id, :public, :source, :source, :image
  has_and_belongs_to_many :articles
  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>',
    large: '640x480>'
  }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_area :caption %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_area :source %>
  </div>
  <div class="field">
    <%= f.label :extension %><br />
    <%= f.text_field :extension %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_area :source %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.number_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :public %><br />
    <%= f.check_box :public %>
  </div>
  <div class="field">
    (bigger than 4MB not advised)
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Caption</th>
    <th>Source</th>
    <th>Extension</th>
    <th>Source</th>
    <th>Person</th>
    <th>Public</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.caption %></td>
    <td><%= photo.source %></td>
    <td><%= photo.extension %></td>
    <td><%= photo.source %></td>
    <td><%= photo.person_id %></td>
    <td><%= photo.public %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<div class="grids">
  <div class="grid-8">

    <%= render 'form' %>

  </div>
  <div class="grid-4">
    <aside class="mky">

      <section class="pf mfb">
        <%= link_to 'Back', photos_path %>
      </section>

    </aside>
  </div>
</div>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @photo.image.url(:medium) %>


<p>
  <b>Caption:</b>
  <%= @photo.caption %>
</p>

<p>
  <b>Source:</b>
  <%= @photo.source %>
</p>

<p>
  <b>Extension:</b>
  <%= @photo.extension %>
</p>

<p>
  <b>Source:</b>
  <%= @photo.source %>
</p>

<p>
  <b>Person:</b>
  <%= @photo.person_id %>
</p>

<p>
  <b>Public:</b>
  <%= @photo.public %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>